name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: test coinwatch
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_get_exchanges_200 ${{ secrets.X_COIN_API_KEY }}
          test_coinwatch_get_list_of_exchanges_by_date_200 ${{ secrets.X_COIN_API_KEY }} 2017-09-17
          test_coinwatch_sh ${{ secrets.X_COIN_API_KEY }} 2017-09-17
