name: ci

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "coinwatch.sh"
    - "test_suite.sh"

env:
  NAME_OF_PROGRAM: coinwatch

jobs:
  test-sh:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install notification dep
        run: |
          sudo apt-get install libnotify-bin

      - name: test coinwatch apis
        env:
          X_COIN_API_KEY: ${{ secrets.X_COIN_API_KEY }}
          NOMICS_API_KEY: ${{ secrets.NOMICS_API_KEY }}
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_get_exchanges_coinapi_200
          test_get_exchanges_messari_200

      - name: test coinwatch shell script
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_coinwatch_sh
          test_coinwatch_history_sh

  test-prelease:
    runs-on: ubuntu-latest
    needs: test-sh
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: get latest version release tag
        id: getlatesttag
        uses: "oprypin/find-latest-tag@v1"
        with:
          repository: icydigital/${{ env.NAME_OF_PROGRAM }}-cli
          releases-only: true

      - name: create the environment
        run: |
          release_tag=${{ steps.getlatesttag.outputs.tag }}
          echo "[DEBUG] VERSION_RELEASE_TAG=$release_tag"

          echo "ARTIFACT_NAME=${{ env.NAME_OF_PROGRAM }}-$release_tag" >> $GITHUB_ENV
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

      - name: get release from release registry
        run: gh release download ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test release
        run: |
          ls -lh && mkdir pre_release
          unzip -d /pre_release ${{ env.ARTIFACT_NAME }}
          chmod +x ./${{ env.NAME_OF_PROGRAM }}
          ls -lh
          ./${{ env.NAME_OF_PROGRAM }}
