name: ci

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "coinwatch.sh"
    - "test_suite.sh"

env:
  NAME_OF_PROGRAM: coinwatch

jobs:
  test-sh:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install notification dep
        run: |
          sudo apt-get install libnotify-bin

      - name: test coinwatch sh
        env:
          X_COIN_API_KEY: ${{ secrets.X_COIN_API_KEY }}
          NOMICS_API_KEY: ${{ secrets.NOMICS_API_KEY }}
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_get_exchanges_coinapi_200
          test_get_exchanges_nomics_200
          test_get_exchanges_messari_200
          test_coinwatch_sh
          test_coinwatch_sh_notification

  test-release:
    runs-on: ubuntu-latest
    needs: test-sh
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: get latest version release tag
        id: get_release_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.1

      - name: create the environment
        run: |
          release_tag=${{ steps.get_release_tag.outputs.tag }}

          echo "ARTIFACT_NAME=${{ env.NAME_OF_PROGRAM }}-binary-$release_tag" >> $GITHUB_ENV

      - name: download artifact
        uses: dawidd6/action-download-artifact@v2.14.1
        with:
          workflow: release.yml
          name: ${{ env.ARTIFACT_NAME }}

      - name: test release
        run: |
          ls
          ./coinwatch
