name: ci

on:
  push:
    paths-ignore:
    - "README.md"

jobs:
  test-sh:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v4.0.0

      - name: test coinwatch apis
        env:
          X_CMC_PRO_SANDBOX_API_KEY: ${{ secrets.X_CMC_PRO_SANDBOX_API_KEY }}
          X_CMC_PRO_API_KEY: ${{ secrets.X_CMC_PRO_API_KEY }}
        run: |
          source test_suite.sh
          test_get_list_of_coins_cmc_sandbox_200
          test_get_list_of_coins_cmc_pro_api_200

      - name: test coinwatch script
        env:
          X_CMC_PRO_API_KEY: ${{ secrets.X_CMC_PRO_API_KEY }}
        run: |
          echo "#### date argument ####"
          ./coinwatch.sh 2023-08-07

          echo "#### no date argument ####"
          ./coinwatch.sh
