name: ci

on:
  push:
    paths:
    - ".github/workflows/ci.yml"
    - "coinwatch.sh"
    - "test_suite.sh"

jobs:
  test-sh:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install notification dep
        run: |
          sudo apt-get install libnotify-bin

      - name: test coinwatch
        env:
          X_COIN_API_KEY: ${{ secrets.X_COIN_API_KEY }}
          NOMICS_API_KEY: ${{ secrets.NOMICS_API_KEY }}
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_get_exchanges_coinapi_200
          test_get_exchanges_nomics_200
          test_get_exchanges_messari_200
          test_coinwatch_sh 2020-09-16
          test_coinwatch_sh_notification 2020-09-16 true

  test-release:
    runs-on: ubuntu-latest
    needs: test-sh
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: download release
        id: downloadrelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: icydigital/coinwatch

      - name: test release without notification
        run: |
          ${{ steps.timeseries.outputs.release }} -s $(date +"%Y-%m-%d")

      - name: test release with notification
        run: |
          ${{ steps.timeseries.outputs.release }} -s $(date +"%Y-%m-%d") true
