name: release

on:
  push:
    paths:
    - ".github/workflows/release.yml"
    tags:
      - 'v*'

env:
  NAME_OF_PROGRAM: coinwatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:neurobin/ppa
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install shc
          sudo apt install dos2unix

      - name: get the pushed version release tag
        id: get_release_tag
        run: |
          pushed_tag=${GITHUB_REF/refs\/tags\//}
          echo "[DEBUG] VERSION_RELEASE_TAG=$pushed_tag"
          echo "VERSION_RELEASE_TAG=$pushed_tag" >> $GITHUB_ENV

      - name: prebuild binary
        run: |
          shc -v -f ./coinwatch.sh && mv coinwatch.sh.x ${{ env.NAME_OF_PROGRAM }}

      - name: set read/execute permissions on prebuild binary
        run: |
          chmod 755 ./coinwatch

      - name: storing prebuild as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.NAME_OF_PROGRAM }}-binary-${{ env.VERSION_RELEASE_TAG }}
          path: ${{ env.NAME_OF_PROGRAM }}

      - name: upload prebuild artifact to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.G_TOKEN }}
          file: ${{ env.NAME_OF_PROGRAM }}
          asset_name: ${{ env.NAME_OF_PROGRAM }}-${{ env.VERSION_RELEASE_TAG }}
          tag: ${{ env.VERSION_RELEASE_TAG }}
          prerelease: true
